language: r
sudo: false

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

git:
  depth: 3

os:
  - linux

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

r_packages:
  - knitr

install:
  - R -e "0" --args --bootstrap-packrat

after_success:
  - Rscript -e 'devtools::install_github("jimhester/covr")'
  - Rscript -e 'covr::codecov()'
