language: r
sudo: true

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

git:
  depth: 3

os:
  - linux

# Deal with the problems of vignette building on travis: i.e. don't do it!
# This results in a warning being raised because there are vignettes
# that are not being built, so make sure that these don't become errors
# that stop the build!

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual
warnings_are_errors: false

r_packages:
  - knitr

before_install:
    - sudo add-apt-repository ppa:no1wantdthisname/ppa -y
    - sudo apt update && sudo apt install libfreetype6

install:
  - R -e "0" --args --bootstrap-packrat

after_success:
  - Rscript -e 'devtools::install_github("jimhester/covr")'
  - Rscript -e 'covr::codecov()'
